name: Build & Test
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run lint:check --if-present
      - run: npm run build --if-present
      - run: npm run test --if-present
      - run: npm run package:pack --if-present
      # - uses: actions/upload-artifact@v4
      #   with:
      #     name: my-artifact
      #     path: releases/
